global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus сам себя
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node-exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Cadvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
      
  # Docker Swarm (опционально)
  - job_name: 'docker-swarm'
    static_configs:
      - targets:
        - 'manager:9323'
        - 'worker1:9323'
        - 'worker2:9323'