version: '3.8'

services:
  app:
    build: .
    image: web-service
    restart: unless-stopped
    ports:
      - target: 4000           # порт в контейнере
        published: 4000        # внешний порт
        protocol: tcp
        mode: ingress          # ⬅️ для балансировки между репликами
    environment:
      - NODE_ENV=production
      - PORT=4000
    deploy:
      replicas: 3  # рекомендуется указать количество реплик
      # placement:
      #   constraints:
      #     # - node.role != manager
      #     # - node.role == worker  # размещать ТОЛЬКО на worker нодах    
      #     # - node.hostname == VPS2
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      monitoring:
        ipv4_address: 172.30.0.10


