global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "rules/container_alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Укажите ваш Alertmanager
          - '45.84.224.156:9093'

scrape_configs:
  # Prometheus сам себя
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9093']

  # Node-exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - '45.84.224.156:9100'
          - '155.212.223.84:9100'
          - '45.12.19.151:9100'      

# Cadvisor
  - job_name: 'cadvisor'
    static_configs:
      # Manager сервер
      - targets: ['45.84.224.156:8080']
        labels:
          instance: 'Manager'
          node_name: 'Manager'
          node_role: 'manager'
      
      # Worker1 сервер  
      - targets: ['155.212.223.84:8080']
        labels:
          instance: 'Worker1'
          node_name: 'Worker1'
          node_role: 'worker'
      
      # Worker2 сервер
      - targets: ['45.12.19.151:8080']
        labels:
          instance: 'Worker2'
          node_name: 'Worker2'
          node_role: 'worker'
